"""Add strength training fields to Workout

Revision ID: a4e330d13a37
Revises: 02c2622085b6
Create Date: 2025-04-13 16:21:58.627124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e330d13a37'
down_revision = '02c2622085b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')
        batch_op.drop_column('exercise_type')

    # ### end Alembic commands ###
